### PR TITLE
Use the new heroics name replacement features during client gen

### PR DESCRIPTION
**Pull request by djcp**
Includes using the new heroics config file feature to make client config
generation more flexible.

### CODE REVIEW

**Comment by djcp** [comment]
CC @mathias

**Comment by djcp** [comment]
There's a couple method name changes probably necessitate a new major release, in addition to a bunch of new methods.

To see the method name changes, look at the diff against master for `lib/platform-api/client.rb` and search for `list_by_add*`.  The old methods are the incorrect `list_by_add_on` and the new ones are the correct (and consistent) `list_by_addon`.

**Comment by djcp** [comment]
I say we cut this version as 1.0.0 and start following semver.

**Comment by mathias** [comment]
The diff looks much better in `client.rb`. And class names still look right for `Addon*`. Cool.

Let's polish up heroics and get it released?

**Pull request merged**
