### PR TITLE
Update with new API endpoints since 2014.

### PR DESCRIPTION
**Pull request by ojacobson**

### CODE REVIEW

**Comment by kenliu** [comment]
+1

**Comment by kenliu** [comment]
@jkakar @brandur is this API still being maintained?

**Comment by geemus** [comment]
@kenliu not as well as we ought to obviously, sorry about that..

**Comment by geemus** [comment]
@ojacobson thanks!

**Comment by geemus** [comment]
Just pushed an even-more-updated 0.3.0

**Comment by kenliu** [comment]
Thank you!

On Tuesday, June 16, 2015, Wesley Beary <notifications@github.com> wrote:

> Just pushed an even-more-updated 0.3.0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/platform-api/pull/28#issuecomment-112482781>.
>


-- 
Sent from my mobile

**Comment by geemus** [comment]
Certainly, it wasn't really intentional, just fell off my radar/I forgot.

**Pull request merged**
