### PR TITLE
Update schema to latest

### PR DESCRIPTION
**Pull request by paul**
Adds support for the pipeline API

### CODE REVIEW

**Comment by geemus** [comment]
Thanks!

**Comment by rmacklin** [comment]
I stumbled upon this PR searching the issues for "pipelines", because I had first searched the API docs and didn't see anything about pipelines. Was it intentional to not publish new docs after this was merged? (Is this not ready for the public?) It looks like the `gh-pages` branch actually hasn't been updated in 6 months. Any info on this would be appreciated. Thanks!

**Comment by geemus** [comment]
Hey, not intentional. I hadn't realized I was failing to push parts, I can take a look. Any/all things that appear in the schema should be some-level-of-public as defined by their stability. You can see that a bit more clearly in the docs on devcenter here: https://devcenter.heroku.com/articles/platform-api-reference#pipeline. Pipeline is currently prototype-stability it would appear, which means that it is public but still new enough that we suspect some changes might still need to happen. Once it gets a bit more battle-tested we would then promote it toward production stability. In the mean time, I'll look into what needs to be done on those docs (which I didn't realize were a thing).

**Comment by geemus** [comment]
I think those docs should be updated now as well, I'll try to stay on top of them better now that I fully realize what needs to be done. Thanks for the heads up.

**Comment by rmacklin** [comment]
No problem, and thanks for updating them!

**Pull request merged**
