### PR TITLE
Update to latest schema.json

### PR DESCRIPTION
**Pull request by calebthompson**

### CODE REVIEW

**Comment by calebthompson** [comment]
Tests are failing due to a Hatchet issue. Working on a PR for that as well. I assume it will be https://github.com/heroku/hatchet/pull/139.

**Comment by schneems** [comment]
Seems good Hatchet 7.3.1 was released with Ruby 2.2 support

**Comment by calebthompson** [comment]
@schneems tests now passing, thanks for merging the Hatchet fix.

**Comment by calebthompson** [comment]
Resolves #98

**Comment by calebthompson** [comment]
Resolves #95 #87 as well I believe.

**Pull request merged**
